apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  selector:
    matchLabels:
      app: backend-app
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend
        # image: backend-app:latest # build `backend-app` image locally.
        image: kakrottt/backend-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: REDIS_URI
            value: "redis://redis-svc:6379"